"""empty message

Revision ID: 1a7c6da8b3a
Revises: None
Create Date: 2015-07-19 23:48:06.602285

"""

# revision identifiers, used by Alembic.
revision = '1a7c6da8b3a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ping_loc', table_name='ping')
    op.alter_column('post', 'image_path', new_column_name='large')
    #op.add_column('post', sa.Column('large', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('medium', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('small', sa.Text(), nullable=True))
    op.drop_index('idx_post_loc', table_name='post')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_post_loc', 'post', ['loc'], unique=False)
    op.drop_column('post', 'small')
    op.drop_column('post', 'medium')
    #op.drop_column('post', 'large')
    op.alter_column('post', 'large', new_column_name='image_path')
    op.create_index('idx_ping_loc', 'ping', ['loc'], unique=False)
    ### end Alembic commands ###
