"""empty message

Revision ID: 3b18793bb56
Revises: None
Create Date: 2018-04-01 09:35:42.276577

"""

# revision identifiers, used by Alembic.
revision = '3b18793bb56'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('loc', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ping_author_id'), 'ping', ['author_id'], unique=False)
    op.create_index(op.f('ix_ping_timestamp'), 'ping', ['timestamp'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('loc', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('large', sa.Text(), nullable=True),
    sa.Column('medium', sa.Text(), nullable=True),
    sa.Column('small', sa.Text(), nullable=True),
    sa.Column('caption', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_author_id'), 'post', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_author_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_ping_timestamp'), table_name='ping')
    op.drop_index(op.f('ix_ping_author_id'), table_name='ping')
    op.drop_table('ping')
    op.drop_table('user')
    ### end Alembic commands ###
